# Replace <PREFIX> with the filename of the script (default is "ev")
# Replace <EV_BATTERY_LEVEL> with the entity_id of the ev battery level sensor or emulated entity_id from this script.

type: vertical-stack
cards:
  - type: markdown
    content: >
      ## 游늹 Kalkulering af ladetab ##


      For at opn친 det bedste resultat anbefales det at lade bilen op fra en lav
      procent (f.eks. 10%) til 100%.


      1. **<font color={% if states.<EV_BATTERY_LEVEL>.state | int >
      20 %}red{% else %}lightgreen{% endif %}>Aflad bilen</font>** :
         - S칮rg for at bilen er afladet s친 meget som muligt.
         - "**{{ states.<EV_BATTERY_LEVEL>.name }}**" er p친 {{ states.<EV_BATTERY_LEVEL>.state }}% (Maksimum 20%).

      2. **<font color={% if
      states.input_number.<PREFIX>_max_recommended_charge_limit_battery_level.state |
      int < 90 %}red{% else %}lightgreen{% endif %}>Indstil max
      ladeprocent</font>**:
         - S칝t den 칮nskede ladeprocent i bilen og Home Assistant.
         - "**{{ states.input_number.<PREFIX>_max_recommended_charge_limit_battery_level.name }}"** er sat til {{ states.input_number.<PREFIX>_max_recommended_charge_limit_battery_level.state }}% (Minimum 90%).

      3. **Aktiver "Kalkulere ladetab"**: Start processen for kalkulering af
      ladetab. Lad bilen selv indikere, n친r den er fuldt opladet.

      4. **Gem resultatet**: N친r opladningen er fuldf칮rt, gemmes resultatet
      automatisk i konfigurationsfilen.

      5. **Modtag notifikation**: Du vil modtage en notifikation p친 din mobil
      med resultatet.
  - type: custom:mushroom-entity-card
    entity: input_boolean.<PREFIX>_calculate_charging_loss
    fill_container: true
  - type: custom:mushroom-title-card
    title: ''
view_layout:
  position: sidebar
