# Required: HACS integration (https://hacs.xyz/)
# Required: lovelace-mushroom (https://github.com/piitaya/lovelace-mushroom)
# Required: numberbox-card (https://github.com/junkfix/numberbox-card)
# Required: stack-in-card (https://github.com/custom-cards/stack-in-card)

type: vertical-stack
cards:
  - type: custom:stack-in-card
    mode: vertical
    cards:
      - type: markdown
        content: >
          ## 📎 Anbefalet fuld ladning


          <details>

          <summary><b>Læs mere</b></summary>


          Hvis din bil har et LFP-batteri anbefales det mindst en gang hver 14.
          dag eller som foreskrevet af bilproducenten.


          </details>
      - type: custom:numberbox-card
        border: true
        entity: input_number.ev_full_charge_recommended
      - type: custom:mushroom-entity-card
        entity: input_datetime.ev_last_full_charge
        fill_container: false
        secondary_info: state
view_layout:
  position: sidebar
