# Required: HACS integration (https://hacs.xyz/)
# Required: lovelace-mushroom (https://github.com/piitaya/lovelace-mushroom)
# Required: stack-in-card (https://github.com/custom-cards/stack-in-card)
#
# Replace <EV_BATTERY_LEVEL> with the entity_id of the ev battery level sensor or emulated entity_id from this script.

type: vertical-stack
cards:
  - type: vertical-stack
    cards:
      - type: custom:stack-in-card
        mode: vertical
        cards:
          - type: markdown
            content: >
              ## 游늹 Ladetab beregning ##


              For at opn친 det bedste resultat anbefales det at lade bilen op fra
              en lav procent (f.eks. 10%) til 100%.


              1. **<font color={% if states.<EV_BATTERY_LEVEL>.state |
              int > 20 %}red{% else %}lightgreen{% endif %}>Aflad bilen</font>**
              :
                 - S칮rg for at bilen er afladet s친 meget som muligt.
                 - "**{{ states.<EV_BATTERY_LEVEL>.name }}**" er p친 {{ states.<EV_BATTERY_LEVEL>.state }}% (Maksimum 20%).

              2. **<font color={% if
              states.input_number.ev_max_recommended_charge_limit_battery_level.state
              | int < 90 %}red{% else %}lightgreen{% endif %}>Indstil max
              ladeprocent</font>**:
                 - S칝t den 칮nskede ladeprocent i bilen og Home Assistant.
                 - "**{{ states.input_number.ev_max_recommended_charge_limit_battery_level.name }}"** er sat til {{ states.input_number.ev_max_recommended_charge_limit_battery_level.state }}% (Minimum 90%).

              3. **Aktiver "Ladetab beregning"**: Start processen for
              ladetab beregningen. Lad bilen selv indikere, n친r den er fuldt
              opladet.

              4. **Gem resultatet**: N친r opladningen er fuldf칮rt, gemmes
              resultatet automatisk i konfigurationsfilen.

              5. **Modtag notifikation**: Du vil modtage en notifikation p친 din
              mobil med resultatet.
          - type: custom:mushroom-entity-card
            entity: input_boolean.ev_calculate_charging_loss
            fill_container: true
    view_layout:
      position: sidebar
  - type: custom:mushroom-chips-card
    chips:
      - type: action
        tap_action:
          action: perform-action
          target: {}
          perform_action: pyscript.ev_update_repo
        hold_action:
          action: more-info
        double_tap_action:
          action: none
        icon: mdi:cloud-download
      - type: entity
        entity: input_button.ev_restart_script
        tap_action:
          action: more-info
        hold_action:
          action: more-info
        double_tap_action:
          action: more-info
        content_info: name
        icon_color: red
        use_entity_picture: false
    alignment: end
    view_layout:
      position: sidebar
view_layout:
  position: sidebar
