# Required: HACS integration (https://hacs.xyz/)
# Required: lovelace-mushroom (https://github.com/piitaya/lovelace-mushroom)
# Required: stack-in-card (https://github.com/custom-cards/stack-in-card)
#
# Replace <EV_BATTERY_LEVEL> with the entity_id of the ev battery level sensor or emulated entity_id from this script.

type: vertical-stack
cards:
  - type: custom:stack-in-card
    mode: vertical
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-entity-card
            entity: input_boolean.ev_fill_up
            double_tap_action:
              action: none
            hold_action:
              action: none
            tap_action:
              action: toggle
            secondary_info: none
          - type: custom:mushroom-entity-card
            border: true
            entity: input_number.ev_typical_daily_distance
            step: 5
            min: 0
            max: 500
      - type: markdown
        content: >-
          # 📎 {{ states.input_boolean.ev_fill_up.name }}


          **Kan aktiveres ved ferie** (Ignorerer arbejdsplanen) 🏖️


          <details>

          <summary><b>Læs mere</b></summary>


          - **📊 Opladning**: Fordeles over en uge.

          - **🔋 Opladningsbehov**:
            - {{ states.input_number.ev_max_recommended_charge_limit_battery_level.state | int - states.<EV_BATTERY_LEVEL>.state | int }}% opdeles i 3 dele.
            - Opladningsbehovet er baseret på forskellen mellem det nuværende batteriniveau og det maksimalt anbefalede.
          - **📅 Opladningsplan**: Finder de billigste tidspunkter for
          opladning.


          </details>
